### ISSUE TITLE
kraken2

### ISSUE THREAD

**Issue by lfaino** [fbreitwieser/pavian#35]
Dear Developer,
i`m trying to use Pavian with Kraken2 report but I get an error. I did a bit of checking and I noted the Kraken results given as examples are different from my outputs. 
the examples have 7 columns while my results have 6 like described at http://ccb.jhu.edu/software/kraken/MANUAL.html.

can you please help me to figure out the problem?

cheers
Luigi

**Comment by timacwalker** [comment]
I've also encountered this issue. Does the admins have a small example data file that works they could publish for comparison. 

Tim.

**Comment by fbreitwieser** [comment]
Hi @lfaino and @timacwalker , thanks for reporting the issue. I added support for Kraken2 report files in the latest version.

**Comment by David-Lee86** [comment]
Hi, I'm having an issue with Pavian. I classified my samples with Kraken2 and added the data to Pavian. Pavian displays the data nicely except for the "Number of reads across all samples ( PDF )" section. I'm getting an error:
Error:factor level [2] is duplicated

Is this due to Kraken2 producing a report with only 6 columns as noted before by @lfaino and @timacwalker?

**Comment by paulapappalardo** [comment]
Hi, I used kraken2 for taxonomic assignment and was trying to use the compare function in pavian to compare some taxa across samples in different treatments. I love pavian, seems like such a great tool! I got the same error mentioned in this issue "Error: factor level [2] is duplicated". I do have 6 columns in the report file from kraken2, so it does not seem that the problem is the report format. I was wondering if there is any additional suggestions about this problem. Thank you very much.
