### ISSUE TITLE
Use pavian to read recentrifuge output

### ISSUE THREAD

**Issue by rdwrt** [fbreitwieser/pavian#37]
Hi, when using recentrifuge ( https://github.com/khyox/recentrifuge ) after centrifuge, the output of recentrifuge cannot be parsed by pavian anymore. There is a column with confidence data added that isn't parsed by pavian and there are some general layout changes compared to centrifuge. What would be a good way to get started fitting recentrifuge output into pavian?

**Comment by fbreitwieser** [comment]
Can you provide example output files from recentrifuge?
Thanks!

**Comment by khyox** [comment]
Hi @rdwrt,
Since Pavian can directly parse the output from Centrifuge, what would be the point of parsing the output of Recentrifuge with Pavian? Are you thinking in using Recentrifuge as a bridge for LMAT or CLARK(S) classifiers that Recentrifuge parses, or are you more interested in the derived samples that Recentrifuge generates (control-subtracted, exclusive, shared...)? Thanks.

**Comment by fbreitwieser** [comment]
Closed due to inactivity, please reopen if you have example files
